packages:
  - apps/*
  - packages/*
catalogs:
  pay:
    react-hook-form: ^7.60.0
    "@solana/web3.js": ^1.98.0
    "@solana/spl-token": ^0.4.13
    "@solana/qr-code-styling": ^1.6.0
    "@solana/pay": ^0.2.5
    bcryptjs: ^3.0.2
    bs58: ^6.0.0
    bignumber.js: ^9.2.1
    clsx: ^2.1.1
    jose: ^6.0.10
    next: ^15.2.3
    react: ^19
    react-dom: ^19
    react-icons: ^5.5.0
    "@marsidev/react-turnstile": ^1.1.0
    "@eslint/eslintrc": ^3
    "@types/node": ^22
    "@types/react": ^19
    "@types/react-dom": ^19
    eslint: ^9
    eslint-config-next: ^15.2.2
    nanoid: ^5.1.5
    qrcode.react: ^4.2.0
    sass: ^1.86.0
    tweetnacl: ^1.0.3
    "@react-hookz/web": ^25.1.1
    prisma: ^6.8.2
    "@prisma/client": ^6.8.2
    typescript: ~5.7.2
    zod: ^3.23.8
    zod-validation-error: ^3.4.0
    "@hookform/resolvers": ^3.9.1
    lucide-react: ^0.525.0
    zustand: ^5.0.3
    "@tailwindcss/postcss": ^4.1.6
    tailwindcss: ^4.1.6
    postcss: ^8.4.49
    pg: ^8.16.3
    "@types/pg": ^8.15.4
    "@radix-ui/react-accordion": ^1.2.11
    "@radix-ui/react-alert-dialog": ^1.1.14
    "@radix-ui/react-aspect-ratio": ^1.1.7
    "@radix-ui/react-avatar": ^1.1.10
    "@radix-ui/react-checkbox": ^1.3.2
    "@radix-ui/react-collapsible": ^1.1.11
    "@radix-ui/react-context-menu": ^2.2.15
    "@radix-ui/react-dialog": ^1.1.14
    "@radix-ui/react-dropdown-menu": ^2.1.15
    "@radix-ui/react-hover-card": ^1.1.14
    "@radix-ui/react-label": ^2.1.7
    "@radix-ui/react-menubar": ^1.1.15
    "@radix-ui/react-navigation-menu": ^1.2.13
    "@radix-ui/react-popover": ^1.1.14
    "@radix-ui/react-progress": ^1.1.7
    "@radix-ui/react-radio-group": ^1.3.7
    "@radix-ui/react-scroll-area": ^1.2.9
    "@radix-ui/react-select": ^2.2.5
    "@radix-ui/react-separator": ^1.1.7
    "@radix-ui/react-slider": ^1.3.5
    "@radix-ui/react-slot": ^1.2.3
    "@radix-ui/react-switch": ^1.2.5
    "@radix-ui/react-tabs": ^1.1.12
    "@radix-ui/react-toggle": ^1.1.9
    "@radix-ui/react-toggle-group": ^1.1.10
    "@radix-ui/react-tooltip": ^1.2.7
    class-variance-authority: ^0.7.1

    cmdk: ^1.1.1
    date-fns: ^4.1.0
    embla-carousel-react: ^8.6.0
    input-otp: ^1.4.2

    next-themes: ^0.4.6

    react-day-picker: ^9.8.0

    react-resizable-panels: ^3.0.3
    recharts: ^2.15.4
    sonner: ^2.0.6
    tailwind-merge: ^3.3.1

    vaul: ^1.1.2
  dashboard:
    "@hookform/resolvers": ^3.9.1
    "@marsidev/react-turnstile": ^1.1.0
    "@radix-ui/react-alert-dialog": ^1.1.2
    "@radix-ui/react-avatar": ^1.1.1
    "@radix-ui/react-checkbox": ^1.1.2
    "@radix-ui/react-collapsible": ^1.1.1
    "@radix-ui/react-dialog": ^1.1.2
    "@radix-ui/react-dropdown-menu": ^2.1.2
    "@radix-ui/react-icons": ^1.3.2
    "@radix-ui/react-label": ^2.1.0
    "@radix-ui/react-popover": ^1.1.2
    "@radix-ui/react-radio-group": ^1.2.1
    "@radix-ui/react-scroll-area": ^1.2.1
    "@radix-ui/react-select": ^2.1.2
    "@radix-ui/react-separator": ^1.1.0
    "@radix-ui/react-slot": ^1.1.0
    "@radix-ui/react-switch": ^1.1.1
    "@radix-ui/react-tabs": ^1.1.1
    "@radix-ui/react-toast": ^1.2.2
    "@radix-ui/react-tooltip": ^1.1.4
    "@radix-ui/react-visually-hidden": ^1.1.0
    "@tabler/icons-react": ^3.24.0
    "@tanstack/react-query": ^5.62.3
    "@tanstack/react-router": ^1.86.1
    "@tanstack/react-table": ^8.20.5
    axios: ^1.7.9
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: 1.0.4
    date-fns: ^4.1.0
    js-cookie: ^3.0.5
    lucide-react: ^0.503.0
    react: ^19.0.0
    react-day-picker: 8.10.1
    react-dom: ^19.0.0
    react-hook-form: ^7.54.0
    react-icons: ^5.5.0
    recharts: ^2.14.1
    tailwind-merge: ^2.5.5
    tailwindcss-animate: ^1.0.7
    vite-plugin-svgr: ^4.3.0
    zod: ^4.1.12
    zod-validation-error: ^5.0.0
    zustand: ^5.0.2
    "@eslint/js": ^9.16.0
    "@faker-js/faker": ^9.3.0
    "@tanstack/eslint-plugin-query": ^5.62.1
    "@tanstack/react-query-devtools": ^5.62.3
    "@tanstack/react-router-devtools": ^1.116.0
    "@tanstack/router-plugin": ^1.86.0
    "@trivago/prettier-plugin-sort-imports": ^4.3.0
    "@types/js-cookie": ^3.0.6
    "@types/node": ^22.10.1
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.1
    "@vitejs/plugin-react-swc": ^3.7.2
    "@tailwindcss/postcss": ^4.1.6
    eslint: ^9.16.0
    eslint-plugin-react-hooks: ^5.1.0
    eslint-plugin-react-refresh: ^0.4.16
    globals: ^15.13.0
    knip: ^5.41.1
    postcss: ^8.4.49
    prettier: ^3.4.2
    prettier-plugin-tailwindcss: ^0.6.11
    tailwindcss: ^4.1.6
    typescript: ~5.7.2
    typescript-eslint: ^8.17.0
    vite: ^6.0.9
  server:
    "dotenv": ^16.5.0
    "fastify": ^5.3.3
    "fastify-plugin": ^5.0.1
    "@fastify/postgres": ^6.0.2
    "nodemon": ^3.1.10
    "p-retry": ^6.2.1
    "pg": ^8.16.0
    "typescript": ^5.7.2
    "ts-node": ^10.9.2
    "@types/node": ^22
    "@fastify/type-provider-typebox": ^5.1.0
    "@sinclair/typebox": ^0.34.33
onlyBuiltDependencies:
  - prisma
  - "@prisma/engines"
